// Fake phone numbers, formatted like real US numbers but always using the
// 555 exchange, which is reserved in North America for fictional use
// (555-0100 through 555-0199 and, for our purposes here, the whole 555-xxxx
// range) so nothing generated by this site can ever collide with a real,
// working telephone number.

function randomDigits(len) {
  let out = '';
  for (let i = 0; i < len; i++) out += Math.floor(Math.random() * 10);
  return out;
}

export function randomAreaCode() {
  // Avoid area codes starting with 0 or 1, mirroring real NANP rules.
  const first = 2 + Math.floor(Math.random() * 8);
  return `${first}${randomDigits(2)}`;
}

export function generateFakeNumber() {
  const area = randomAreaCode();
  const line = randomDigits(4);
  return `(${area}) 555-${line}`;
}

export function normalizeSearch(input) {
  return (input || '').replace(/[^\d]/g, '');
}

export function numberContainsDigits(phoneNumber, digits) {
  if (!digits) return true;
  return phoneNumber.replace(/[^\d]/g, '').includes(digits);
}
